name: Cypress Nightly

on:
  schedule:
    # runs e2e tests every day at 4am
    - cron: '0 4 * * *'

env:
  REGISTRY: ghcr.io
  NAME: nrfesampleapp

jobs:
  e2e-chrome:
    runs-on: ubuntu-20.04
    name: E2E on Chrome
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
      
      - name: Upload screenshots on failure
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots-chrome
          path: cypress/screenshots
      
      - name: Upload videos
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-videos-chrome
          path: cypress/videos
  
  e2e-firefox:
    runs-on: ubuntu-20.04
    container:
      image: cypress/included:11.2.0
      options: --user 1001
    name: E2E on Firefox
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Cypress run
        run: cypress run --browser firefox
      
      - name: Upload screenshots on failure
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots-firefox
          path: cypress/screenshots
      
      - name: Upload videos
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-videos-firefox
          path: cypress/videos

  e2e-edge:
    runs-on: windows-latest
    name: E2E on Edge
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          browser: edge
      
      - name: Upload screenshots on failure
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots-edge
          path: cypress/screenshots
      
      - name: Upload videos
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-videos-edge
          path: cypress/videos
