name: cypress-nightly

on:
  schedule:
    # runs e2e tests every day at 4am
    - cron: '0 4 * * *'

env:
  REGISTRY: ghcr.io
  NAME: nrfesampleapp

jobs:
  e2e-chrome:
    runs-on: ubuntu-20.04
    name: E2E on Chrome
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
      
      - name: Upload screenshots on failure
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots-chrome
          path: cypress/screenshots
      
      - name: Upload videos
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-videos-chrome
          path: cypress/videos
  
  e2e-firefox:
    runs-on: ubuntu-20.04
    name: E2E on Firefox
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          browser: firefox
      
      - name: Upload screenshots on failure
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots-firefox
          path: cypress/screenshots
      
      - name: Upload videos
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-videos-firefox
          path: cypress/videos

  e2e-webkit:
    runs-on: ubuntu-20.04
    name: E2E on Webkit
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install dependencies
        uses: cypress-io/github-action@v4
        with:
          # install WebKit browser dependencies
          build: npx playwright install-deps webkit
          runTests: false

      - name: Cypress run (WebKit)
        uses: cypress-io/github-action@v4
        with:
          # we have already installed everything
          install: false
          browser: webkit
      
      - name: Upload screenshots on failure
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots-webkit
          path: cypress/screenshots
      
      - name: Upload videos
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-videos-webkit
          path: cypress/videos

  e2e-edge:
    runs-on: windows-latest
    name: E2E on Edge
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          browser: edge
      
      - name: Upload screenshots on failure
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots-edgecypress
          path: cypress/screenshots
      
      - name: Upload videos
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-videos-edge
          path: cypress/videos
